# Generated by Django 4.0.1 on 2022-01-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='ФИО')),
                ('login_jira', models.CharField(max_length=100, unique=True)),
                ('monday', models.BooleanField(blank=True, default=False, verbose_name='пн')),
                ('tuesday', models.BooleanField(blank=True, default=False, verbose_name='вт')),
                ('wednesday', models.BooleanField(blank=True, default=False, verbose_name='ср')),
                ('thursday', models.BooleanField(blank=True, default=False, verbose_name='чт')),
                ('friday', models.BooleanField(blank=True, default=False, verbose_name='пт')),
                ('saturday', models.BooleanField(blank=True, default=False, verbose_name='сб')),
                ('sunday', models.BooleanField(blank=True, default=False, verbose_name='вс')),
                ('start_time', models.TimeField(null=True, verbose_name='Начало работы')),
                ('final_time', models.TimeField(null=True, verbose_name='Конец работы')),
                ('day_limit', models.IntegerField(default=45, verbose_name='Дневной лимит')),
                ('counter', models.IntegerField(default=0, verbose_name='Назначенных задач')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('hour_limit', models.IntegerField(default=7, verbose_name='Лимит в час')),
                ('hour_counter', models.IntegerField(default=0, verbose_name='Назначенных за час')),
                ('start_time_online', models.TimeField(default=None, null=True, verbose_name='Вошел в линию')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='managers.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': '1',
                'verbose_name_plural': '1d',
                'ordering': ['full_name'],
            },
        ),
    ]
