# Generated by Django 4.0.1 on 2022-01-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['full_name'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.CreateModel(
            name='Path_JQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_jql', models.TextField(default=None, unique=True, verbose_name='Запрос JQL')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.group', verbose_name='Группа')),
            ],
        ),
    ]
