# Generated by Django 4.0.1 on 2022-01-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_manager_options_path_jql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['group'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='path_jql',
            options={'verbose_name': 'Запрос JQL', 'verbose_name_plural': 'Запросы JQL'},
        ),
    ]
