# Generated by Django 4.0.1 on 2022-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_manager_options_alter_path_jql_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
