# Generated by Django 4.0.1 on 2022-02-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['full_name'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
    ]
