# Generated by Django 4.0.1 on 2022-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_key_customers',
            options={'ordering': ['id'], 'verbose_name': 'Метка', 'verbose_name_plural': 'Метки ключевых клиентов'},
        ),
        migrations.AddField(
            model_name='contract_key_customers',
            name='description',
            field=models.TextField(default=1231, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
