# Generated by Django 4.0.1 on 2022-02-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_alter_group_options'),
        ('setting_label', '0003_alter_contract_key_customers_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers_for_SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_sms', models.BooleanField(blank=True, default=False, verbose_name='Отправка СМС')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager', verbose_name='ФИО')),
            ],
        ),
    ]
