# Generated by Django 4.0.1 on 2022-02-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_alter_manager_options'),
        ('setting_label', '0006_alter_managers_for_sms_additionalphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers_for_sms',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager', unique=True, verbose_name='ФИО'),
        ),
    ]
